name: touch_craft_editor
description: "Craft stunning visual editors with Flutter. ğŸ¨ Add text, GIFs, stickers, gradients, and images â€” customize everything, export anywhere, and re-edit anytime."
version: 0.0.1
repository: https://github.com/avni-7span/touch_craft_editor
issue_tracker: https://github.com/avni-7span/touch_craft_editor/issues
platforms:
  android:
  ios:

screenshots:
  path: touch_craft_editor.jpg


environment:
  sdk: ^3.3.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  crop_image: ^1.0.16
  enough_giphy: ^0.2.1
  enough_platform_widgets: ^1.1.1
  tflite_flutter: ^0.11.0
  image: ^4.1.3
  screen_recorder: ^0.3.0
  connectivity_plus: ^6.1.4
  saver_gallery: ^4.0.1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

